#!/usr/bin/env julia

using Pkg

Pkg.activate("compilestuff", shared=true)
Pkg.add("PackageCompiler")

insert!(LOAD_PATH, 2, "@compilestuff")

@info LOAD_PATH
println("TADA 1")
println(LOAD_PATH)

Pkg.activate(".")

@info LOAD_PATH
println("TADA 2")
println(LOAD_PATH)

using PackageCompiler

@info "HERE DONE"
println("TADA 3")

ENV["JULIA_LOAD_PATH"] = "@:@compilestuff:@v#.#:@stdlib"

path_a, path_b = compile_incremental(:VegaDatasets)

@info path_a
@info path_b

using IJulia

installkernel("Julia", "--project=$(@__DIR__) --J $(path_b)"
