#!/usr/bin/env julia

using Pkg

Pkg.activate("compilestuff", shared=true)
Pkg.add("PackageCompiler")

insert!(LOAD_PATH, 2, "@compilestuff")

Pkg.activate(".")

using PackageCompiler

# Our LOAD_PATH modifications are not passed through to client processes
# by PackageCompiler, so we use this hack to make sure our LOAD_PATH
# is also used by the client processes
ENV["JULIA_LOAD_PATH"] = "@:@compilestuff:@v#.#:@stdlib"

ENV["JULIA_PROJECT"] = @__DIR__

path_a, path_b = compile_incremental(:VegaDatasets)

@info path_a
@info path_b

using IJulia

installkernel("Julia", "--project=$(@__DIR__) --J $(path_b)"
